# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.5'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: '$(System.DefaultWorkingDirectory)/terraformcode/terraformcode'
    backendServiceArm: 'saim-project'
    backendAzureRmResourceGroupName: 'saim-terraform'
    backendAzureRmStorageAccountName: 'saimterraform'
    backendAzureRmContainerName: 'terraformstate'
    backendAzureRmKey: 'nNIYkcjqIcHwtM816PYjdc5t4wxFnRXU5Lr3cgf58s2lB0n1DRrwc/v7xmHT6EjHkHdCmOEUHrWw+AStWX6F6Q=='


- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'validate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'